# Nivell 1

##1. Importa com un DataFrame l'arxiu sprint10.xlsx.
* Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.
* Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.
* Mostra les primeres 10 files. Addicionalment, fes un print on comprovi que el DNI només té valors únics.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('/content/sprint10.xlsx')
df.head()

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
3,0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,True,Grup B
4,1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,True,NaN,Grup A

In [2]:
# header y index_col
# hacemos de la fila 3 el header y definimos el index como la columna 0

df = pd.read_excel('/content/sprint10.xlsx', header = 3, index_col = 0)
df.head()

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A

In [3]:
# sort.values(by=[])
# lo ordemamos primero por pais y despues por ciudad

df_pais = df.sort_values(by=["País d'origen", 'Ciutat'])
df_pais.head(10)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

In [4]:
# is_unique
# te devuelve True si todos los valores son únicos

print("¿Son todos los DNI únicos?:", df_pais['DNI'].is_unique)

¿Son todos los DNI únicos?: True

##2. Crea una columna que sigui el nom complet.
* Crea una columna si la persona és nascuda a Espanya o no.
* Posa el DNI com a índex del DataFrame (noms de files).
* Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
* Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
* Mostra tots els canvis que has realitzat en una sola taula.

In [5]:
# df[] = df[] + df[]
# creamos una columna a partir de otra o otras

df['Nombre_Completo'] = df['Nom'] + ' ' + df['Cognoms']
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B,Inês Ferreira Silva
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A,Clara Sánchez Martínez
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A,Fatima Fassi
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B,Khadija Bennani Bennani
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A,Toni Sánchez García
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B,Marta Ferrer Ferrer
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A,Joan García
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A,Laia Ferrer Martínez
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C,Jordi García
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A,Clara Sánchez López

In [6]:
# creamos columna con .apply(lambda x: función)

df['Nacido en España'] = df["País d'origen"].apply(lambda x: 'Si' if x == 'Espanya' else 'No')
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Nacido en España
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B,Inês Ferreira Silva,No
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A,Clara Sánchez Martínez,Si
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A,Fatima Fassi,No
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B,Khadija Bennani Bennani,No
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A,Toni Sánchez García,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B,Marta Ferrer Ferrer,Si
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A,Joan García,Si
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A,Laia Ferrer Martínez,Si
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C,Jordi García,Si
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A,Clara Sánchez López,Si

In [7]:
# definimos una columna como index

df = df.set_index('DNI')
df.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Nacido en España
DNI,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B,Inês Ferreira Silva,No
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A,Clara Sánchez Martínez,Si
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A,Fatima Fassi,No
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B,Khadija Bennani Bennani,No
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A,Toni Sánchez García,Si

In [8]:
 # renombrar columnas

df = df.rename(columns={'Dia de Naixement': 'Dia', 'Mes de Naixement': 'Mes', 'Any de Naixement': 'Any'})
df.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Nacido en España
DNI,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B,Inês Ferreira Silva,No
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A,Clara Sánchez Martínez,Si
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A,Fatima Fassi,No
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B,Khadija Bennani Bennani,No
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A,Toni Sánchez García,Si

In [9]:
# replace
# cambiar valores

df['Gènere'] = df['Gènere'].replace({'H': 'Home', 'D': 'Dona', 'A': 'Altres', 'NC': np.nan})
df.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Nacido en España
DNI,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,NaN,1.0,Grup B,Inês Ferreira Silva,No
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,1.0,NaN,Grup A,Clara Sánchez Martínez,Si
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,1.0,NaN,Grup A,Fatima Fassi,No
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,NaN,1.0,Grup B,Khadija Bennani Bennani,No
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,NaN,1.0,Grup A,Toni Sánchez García,Si

##3. Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema.
* La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

In [10]:
# definimos la función

def determinar_fills(fila):
    if pd.notna(fila['Fills']):
        return 'Sí'
    else:
        return 'No'

# aplicamos

df['Fills'] = df.apply(determinar_fills, axis=1)

# borramos la columna 'No fills'
df = df.drop('No Fills', axis=1)
df.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nombre_Completo,Nacido en España
DNI,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,No,Grup B,Inês Ferreira Silva,No
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,Sí,Grup A,Clara Sánchez Martínez,Si
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,Sí,Grup A,Fatima Fassi,No
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,No,Grup B,Khadija Bennani Bennani,No
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,No,Grup A,Toni Sánchez García,Si

##4. Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.
* Ordena la taula en funció del sou mig.

In [11]:
#podemos usar describe() y si queremos decir que columnas queremos adicionamos .[['mean','count','50%', 'max']]
#df_genere = df.groupby('Gènere')['Salari mensual'].describe().sort_values(by='mean', ascending=False).round(2)

# la columna está como string, hay que pasarla a float
df['Salari mensual'] = df['Salari mensual'].astype(str).str.replace(' €', '').astype(float)

df_genere = df.groupby('Gènere')['Salari mensual'].agg(['mean','median','min','max']).sort_values(by='mean', ascending=False).round(2)
df_genere

          mean  median   min    max
Gènere
Dona    162.23    1.63  1.00  999.0
Altres  132.22    1.82  1.02  996.0
Home     98.33    1.67  1.00  997.0

##5. Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).
* Afegeix-hi les mitjanes als marges de la taula.
* EXTRA: Aplica format condicional a la taula per veure en un color més intens els valors més elevats

In [12]:
# hacemos el pivot table: definimos el index como genero, pais como columna y como values el sueldo y para la media aggfunc
df_pivot = df.pivot_table(index='Gènere', columns="País d'origen", values='Salari mensual', aggfunc='mean', margins = True, margins_name='Media')

# para el heat map usamos la funcion .background_gradient(cmap=)
# el round no me funciona al declarar df_pivot, por el .style, asi que lo definimos despues con format
df_pivot.style.format("{:.2f}").background_gradient(cmap='Blues')

##6. Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any.
* Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.
* Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [13]:
# se hace asi: df['Data_naixement'] = pd.to_datetime(df[['any', 'mes', 'dia']])
# pero python solo lo reconoce si los nombres de las columnas son: 'year', 'month', 'day'

# asi que llamamos la columna y la convertemos en str, el errors='coerce' es por si encuentra un error, le decimos que devuelva NaT (not a time)
df['Data_naixement'] = pd.to_datetime(df['Dia'].astype(str) + '-' +
                                      df['Mes'].astype(str) + '-' +
                                      df['Any'].astype(str),
                                      errors='coerce')
df

/tmp/ipython-input-609763773.py:5: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Data_naixement'] = pd.to_datetime(df['Dia'].astype(str) + '-' +

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nombre_Completo,Nacido en España,Data_naixement
DNI,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144,No,Grup B,Inês Ferreira Silva,No,1953-02-25
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253,Sí,Grup A,Clara Sánchez Martínez,Si,1996-03-18
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441,Sí,Grup A,Fatima Fassi,No,2005-11-06
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944,No,Grup B,Khadija Bennani Bennani,No,1995-01-20
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043,No,Grup A,Toni Sánchez García,Si,1999-08-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1.216,No,Grup B,Marta Ferrer Ferrer,Si,1951-06-01
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971.000,No,Grup A,Joan García,Si,1959-04-11
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682.000,No,Grup A,Laia Ferrer Martínez,Si,1980-11-11
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1.699,Sí,Grup C,Jordi García,Si,1984-05-23
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1.217,No,Grup A,Clara Sánchez López,Si,1952-08-01

In [14]:
from datetime import date

def calcular_edat(data_naixement):
    if pd.isna(data_naixement):  # Si la fecha no existe (NaT)
        return None

    avui = date.today()
    # si todavia no ha llegado el dia del cumpleaños, la comparacion te devuelve True, que es igual a 1, así te devuelve la edad bien, le faltan unos dias todavia para el cumple de este año
    return avui.year - data_naixement.year - ((avui.month, avui.day) < (data_naixement.month, data_naixement.day)) # si te devuelve True

df['Edat'] = df['Data_naixement'].apply(calcular_edat)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nombre_Completo,Nacido en España,Data_naixement,Edat
DNI,,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144,No,Grup B,Inês Ferreira Silva,No,1953-02-25,72
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253,Sí,Grup A,Clara Sánchez Martínez,Si,1996-03-18,29
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441,Sí,Grup A,Fatima Fassi,No,2005-11-06,19
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944,No,Grup B,Khadija Bennani Bennani,No,1995-01-20,30
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043,No,Grup A,Toni Sánchez García,Si,1999-08-09,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1.216,No,Grup B,Marta Ferrer Ferrer,Si,1951-06-01,74
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971.000,No,Grup A,Joan García,Si,1959-04-11,66
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682.000,No,Grup A,Laia Ferrer Martínez,Si,1980-11-11,44
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1.699,Sí,Grup C,Jordi García,Si,1984-05-23,41
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1.217,No,Grup A,Clara Sánchez López,Si,1952-08-01,73

#2. Nivell 2

##1. Utilitzant el següent DataFrame, adjunta la columna "Increment" al dataframe del nivell anterior.
* Actualitza la columna salari en funció dels percentatges que s'adjunten. No modifiquis manualment els increments, escriu codi Python per fer les conversions necessàries.
```
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":

["5%","3,5%","2%","8%"]})
```

In [15]:
# creamos df_increment
df_increment = pd.DataFrame({
    "Grup": ["Grup A", "Grup B", "Grup C", "Grup D"],
    "Increment": ["5%", "3,5%", "2%", "8%"]
})

# limpiamos la columna "Increment" y la convertimos en float, dividimos per 100 para tener el valor percentual (ex: 5 -> 0.05)
df_increment['Increment'] = df_increment['Increment'].str.replace(',', '.').str.replace('%', '').astype(float) / 100


# merge df_increment a df
df_actualizado = pd.merge(df, df_increment, left_on='Grup Professional', right_on='Grup', how='left')

# 4. Actualitzem el salari. El nou salari és: Salari_Actual * (1 + Increment)
df_actualizado['Salari mensual'] = df_actualizado['Salari mensual'] * (1 + df_actualizado['Increment'])

df_actualizado.head()

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nombre_Completo,Nacido en España,Data_naixement,Edat,Grup,Increment
0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.18404,No,Grup B,Inês Ferreira Silva,No,1953-02-25,72,Grup B,0.035
1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.31565,Sí,Grup A,Clara Sánchez Martínez,Si,1996-03-18,29,Grup A,0.050
2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.51305,Sí,Grup A,Fatima Fassi,No,2005-11-06,19,Grup A,0.050
3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,2.01204,No,Grup B,Khadija Bennani Bennani,No,1995-01-20,30,Grup B,0.035
4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.09515,No,Grup A,Toni Sánchez García,Si,1999-08-09,26,Grup A,0.050

## 2. Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.

* Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...

* Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.

In [16]:
# obtenemos la lista única de Grupos Profesionales con .unique()
grupos_profesionales = df_actualizado['Grup Professional'].unique()

# bucle para exportar un fichero por grupo
for grupo in grupos_profesionales:
    # Filtramos el DataFrame para cada grupo
    df_grupo = df_actualizado[df_actualizado['Grup Professional'] == grupo] # separamos por grupo (A,B,C,D)

    # Creamos un nombre de fichero dinámico (ej: "datos_GrupA.xlsx")
    # Quitamos espacios del nombre del grupo para el nombre del fichero (ej: Grup A -- GrupA)
    nombre_archivo = f"datos_{grupo.replace(' ', '')}.xlsx"

    # Exportamos a Excel. index=False evita que se guarde el índice (DNI) como columna
    df_grupo.to_excel(nombre_archivo, index=False)
    print(f"Exportado: {nombre_archivo}")

# 3. Creamos el 5º DataFrame de resumen
#    Agrupamos por 'Grup Professional' y calculamos las métricas pedidas
resumen_grupos = df_actualizado.groupby('Grup Professional').agg(
    Numero_Trabajadores=('Nom', 'count'),      # Contamos cuántos nombres hay
    Sueldo_Medio=('Salari mensual', 'mean'),      # Calculamos la media del salario
    Edad_Mediana=('Edat', 'median')            # Calculamos la mediana de la edad
)

# 4. Exportamos el resumen a un 5º fichero
resumen_grupos.to_excel("resumen_grupos_profesionales.xlsx")
print("Exportado: resumen_grupos_profesionales.xlsx")

# 5. Imprimimos el resumen por pantalla (con los valores numéricos float)
print("\nDataFrame de resumen (datos numéricos en bruto):")
print(resumen_grupos)

Exportado: datos_GrupB.xlsx
Exportado: datos_GrupA.xlsx
Exportado: datos_GrupD.xlsx
Exportado: datos_GrupC.xlsx
Exportado: resumen_grupos_profesionales.xlsx

DataFrame de resumen (datos numéricos en bruto):
                   Numero_Trabajadores  Sueldo_Medio  Edad_Mediana
Grup Professional
Grup A                             490    274.955023          50.0
Grup B                             318      1.724551          47.0
Grup C                             137      2.289193          51.0
Grup D                              55      3.100817          43.0

# Nivell 3
El nivell 3 d’aquest sprint és totalment diferent a d’altres sprints que has fet fins ara, ja que són exercicis més abstractes que requereixen barallar-s’hi bastant. No continuen amb el mateix dataset dels nivells anteriors, sinó que et plantegen dues situacions noves totalment diferents entre elles.

## 1. Crea una funció que prengui un dataframe com a paràmetre d'entrada.

* La funció ha de crear (i exportar) un gràfic automàticament per a cada columna del dataframe. Per exemple:
```
un histograma/boxplot si la variable és numèrica
unes barres dels valors més freqüents si és categòrica
unes barres dels anys més freqüents si la dada està en format data.
```
* La idea és crear una funció que funcioni per **qualsevol** dataframe, no només amb el que hem treballat fins ara.

* Mostra el resultat de la funció en algun dels datasets d’exemple que conté el paquet seaborn. Per exemple, iris, penguins o titanic.

**Tingues en consideració que en el següent sprint treballaràs exclusivament amb gràfics. L’objectiu d’aquest exercici no és crear gràfics molt elaborats, sinó resoldre una necessitat de manera ràpida i automàtica.**

In [17]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Ya importado, pero por si acaso
from pandas.api.types import is_numeric_dtype, is_datetime64_any_dtype, is_object_dtype

# 1. Definimos la función
def generar_graficos_auto(dataframe, path_prefix="grafico_"):
    """
    Recorre cada columna de un DataFrame y genera y guarda un gráfico apropiado
    para su tipo de dato.
    """

    # Iteramos sobre cada nombre de columna
    for col in dataframe.columns:
        print(f"Procesando columna: {col}")

        # Creamos una nueva figura para cada gráfico
        plt.figure(figsize=(10, 6))

        try:
            # Opción 1: Si la columna es NUMÉRICA
            if is_numeric_dtype(dataframe[col]):
                sns.histplot(dataframe[col], kde=True, bins=30)
                plt.title(f"Histograma de {col}")
                plt.xlabel(col)
                plt.ylabel("Frecuencia")

            # Opción 2: Si la columna es de tipo FECHA/HORA
            elif is_datetime64_any_dtype(dataframe[col]):
                # Extraemos el año y contamos los valores
                anyos = dataframe[col].dt.year.value_counts().sort_index()
                sns.barplot(x=anyos.index, y=anyos.values)
                plt.title(f"Recuento por Año en {col}")
                plt.xlabel("Año")
                plt.ylabel("Recuento")

            # Opción 3: Si es CATEGÓRICA (object, string, category)
            # O si tiene pocos valores únicos (puede ser numérica pero categórica, como 'Pclass' 1, 2, 3)
            elif is_object_dtype(dataframe[col]) or dataframe[col].nunique() < 20:
                # Contamos los valores más frecuentes (top 15)
                top_15_categorias = dataframe[col].value_counts().nlargest(15).index
                sns.countplot(data=dataframe, x=col, order=top_15_categorias)
                plt.title(f"Recuento de valores más frecuentes en {col}")
                plt.xlabel(col)
                plt.ylabel("Recuento")
                plt.xticks(rotation=45) # Giramos las etiquetas por si son largas

            # Si no cumple nada, lo saltamos
            else:
                print(f"   -> Columna {col} saltada (tipo no manejado o demasiadas categorías).")
                plt.close() # Cerramos la figura vacía
                continue # Pasamos a la siguiente iteración del bucle

            # 3. Guardamos el gráfico en un fichero
            nombre_archivo_grafico = f"{path_prefix}{col}.png"
            plt.tight_layout() # Ajusta el gráfico para evitar cortes
            plt.savefig(nombre_archivo_grafico)
            print(f"   -> Gráfico guardado como: {nombre_archivo_grafico}")

        except Exception as e:
            print(f"   -> ERROR al procesar {col}: {e}")

        finally:
            plt.close() # Cerramos la figura para liberar memoria (muy importante)

# 2. Probamos la función con el dataset 'titanic' de Seaborn
print("\n--- Probando con el dataset 'titanic' ---")
titanic = sns.load_dataset('titanic')
generar_graficos_auto(titanic, path_prefix="titanic_")

print("\n--- Probando con nuestro dataset 'df_actualizado' ---")
# (Nos aseguramos de que Data_naixement sea datetime)
df_actualizado['Data_naixement'] = pd.to_datetime(df_actualizado['Data_naixement'])
generar_graficos_auto(df_actualizado, path_prefix="trabajadores_")

--- Probando con el dataset 'titanic' ---
Procesando columna: survived
   -> Gráfico guardado como: titanic_survived.png
Procesando columna: pclass
   -> Gráfico guardado como: titanic_pclass.png
Procesando columna: sex
   -> Gráfico guardado como: titanic_sex.png
Procesando columna: age
   -> Gráfico guardado como: titanic_age.png
Procesando columna: sibsp
   -> Gráfico guardado como: titanic_sibsp.png
Procesando columna: parch
   -> Gráfico guardado como: titanic_parch.png
Procesando columna: fare
   -> Gráfico guardado como: titanic_fare.png
Procesando columna: embarked
   -> Gráfico guardado como: titanic_embarked.png
Procesando columna: class
   -> Gráfico guardado como: titanic_class.png
Procesando columna: who
   -> Gráfico guardado como: titanic_who.png
Procesando columna: adult_male
   -> Gráfico guardado como: titanic_adult_male.png
Procesando columna: deck
   -> Gráfico guardado como: titanic_deck.png
Procesando columna: embark_town
   -> Gráfico guardado como: titanic_embark_town.png
Procesando columna: alive
   -> Gráfico guardado como: titanic_alive.png
Procesando columna: alone
   -> Gráfico guardado como: titanic_alone.png

--- Probando con nuestro dataset 'df_actualizado' ---
Procesando columna: Nom
   -> Gráfico guardado como: trabajadores_Nom.png
Procesando columna: Cognoms
   -> Gráfico guardado como: trabajadores_Cognoms.png
Procesando columna: País d'origen
   -> Gráfico guardado como: trabajadores_País d'origen.png
Procesando columna: Ciutat
   -> Gráfico guardado como: trabajadores_Ciutat.png
Procesando columna: Dia
   -> Gráfico guardado como: trabajadores_Dia.png
Procesando columna: Mes
   -> Gráfico guardado como: trabajadores_Mes.png
Procesando columna: Any
   -> Gráfico guardado como: trabajadores_Any.png
Procesando columna: Gènere
   -> Gráfico guardado como: trabajadores_Gènere.png
Procesando columna: Salari mensual
   -> Gráfico guardado como: trabajadores_Salari mensual.png
Procesando columna: Fills
   -> Gráfico guardado como: trabajadores_Fills.png
Procesando columna: Grup Professional
   -> Gráfico guardado como: trabajadores_Grup Professional.png
Procesando columna: Nombre_Completo
   -> Gráfico guardado como: trabajadores_Nombre_Completo.png
Procesando columna: Nacido en España
   -> Gráfico guardado como: trabajadores_Nacido en España.png
Procesando columna: Data_naixement
   -> Gráfico guardado como: trabajadores_Data_naixement.png
Procesando columna: Edat
   -> Gráfico guardado como: trabajadores_Edat.png
Procesando columna: Grup
   -> Gráfico guardado como: trabajadores_Grup.png
Procesando columna: Increment
   -> Gráfico guardado como: trabajadores_Increment.png

##2. Carrega l'arxiu matriu_distancies.xlsx a pandas, de manera que els noms de files i els noms de columnes siguin els de les ciutats. Borra "Las Palmas de Gran Canaria" i "Palma" perquè poguem fer el trajecte en cotxe.

Font: Mejores Rutas

* Ens interessa visitar totes les ciutats principals d'Espanya recorrent la mínima distància possible.

* No cal que ho facis de forma òptima, ens interessa que desenvolupis una solució raonable utilitzant les eines que tens actualment.

* Per exemple, una aproximació senzilla (que no òptima) seria anant sempre a la ciutat més propera que no haguem visitat encara

* Fes una funció que donada la matriu de distàncies i la ciutat d'origen, faci una proposta de ruta que sigui el més curta possible que puguis, retornant una llista amb l'ordre de visita. Dóna també la distància total recorreguda.

* EXTRA: Des de quina ciutat la ruta seria més curta amb l'algoritme plantejat

In [39]:
import pandas as pd
import numpy as np

# --- Parte 1: Carga y Limpieza de Datos ---

print("Cargando y limpiando la matriz de distancias...")

# Cargamos el fichero Excel.
try:
    matriz_distancias = pd.read_excel("matriu_distancies.xlsx", index_col=0)
except FileNotFoundError:
    print("AVISO: No se ha encontrado 'matriu_distancies.xlsx', utilizando la ruta completa '/content/...'")
    matriz_distancias = pd.read_excel("/content/matriu_distancies.xlsx", index_col=0)
except Exception as e:
    print(f"Ha ocurrido un error al leer el archivo: {e}")

# Definimos las ciudades a borrar (las islas)
ciudades_a_borrar = ["Las Palmas de Gran Canaria", "Palma"]

# Borramos las ciudades de las filas (index) y de las columnas (columns)
matriz_limpia = matriz_distancias.drop(index=ciudades_a_borrar, columns=ciudades_a_borrar, errors='ignore')

# Limpiamos espacios en blanco del índice y de las columnas
matriz_limpia.index = matriz_limpia.index.str.strip()
matriz_limpia.columns = matriz_limpia.columns.str.strip()

# Forzamos que todos los datos sean numéricos
# (Quitamos los puntos de miles, ej: "2.778" -> "2778")
for col in matriz_limpia.columns:
    if matriz_limpia[col].dtype == 'object': # Si es texto...
        matriz_limpia[col] = matriz_limpia[col].astype(str).str.replace('.', '', regex=False)

    # Convertimos a número (los errores serán NaT)
    matriz_limpia[col] = pd.to_numeric(matriz_limpia[col], errors='coerce')

# Rellenamos cualquier NaN (incluidos los de la diagonal) con 0
matriz_limpia = matriz_limpia.fillna(0)

print(f"Matriz cargada y lista: {len(matriz_limpia)} ciudades peninsulares.")
print("-" * 50)

Cargando y limpiando la matriz de distancias...
Matriz cargada y lista: 13 ciudades peninsulares.
--------------------------------------------------

In [40]:
# --- Parte 2: Definición de la Función ---

def calcular_ruta_corta(matriz, ciudad_origen):
    """
    Calcula una ruta visitando todas las ciudades con el algoritmo del 'vecino más cercano'.
    Devuelve la ruta (lista de ciudades) y la distancia total recorrida.
    """

    ciudades_a_visitar = list(matriz.index)

    if ciudad_origen not in ciudades_a_visitar:
        return f"Error: La ciudad '{ciudad_origen}' no existe en la matriz.", 0

    ruta = [ciudad_origen]
    ciudades_a_visitar.remove(ciudad_origen)
    distancia_total = 0
    ciudad_actual = ciudad_origen

    while ciudades_a_visitar:
        distancias = matriz.loc[ciudad_actual]
        distancias_restantes = distancias[ciudades_a_visitar]
        distancias_sin_cero = distancias_restantes[distancias_restantes > 0]

        if not distancias_sin_cero.empty:
            distancia_viaje = distancias_sin_cero.min()
            ciudad_proxima = distancias_sin_cero.idxmin()
        else:
            distancia_viaje = distancias_restantes.min()
            ciudad_proxima = distancias_restantes.idxmin()

        distancia_total += distancia_viaje
        ciudad_actual = ciudad_proxima
        ruta.append(ciudad_actual)
        ciudades_a_visitar.remove(ciudad_actual)

    return ruta, distancia_total

print("Función 'calcular_ruta_corta' definida.")

Función 'calcular_ruta_corta' definida.

In [42]:
# --- Parte 3: Prueba de la Función ---

print("Prueba de la función comenzando por 'Barcelona':")

# Usamos 'Barcelona' porque SÍ está en la lista de 13 ciudades.
ruta_test, dist_test = calcular_ruta_corta(matriz_limpia, 'Barcelona')

if isinstance(ruta_test, list):
    print(f"Ciudades visitadas: {len(ruta_test)}")
    print(f"Distancia total: {dist_test:.0f} km")
    # Mostramos solo el principio y el final de la ruta
    print(f"Ruta: {' -> '.join(ruta_test[:5])} ... {' -> '.join(ruta_test[-3:])}")
else:
    # Si la ciudad no se encuentra, mostrará el error
    print(ruta_test)

Prueba de la función comenzando por 'Barcelona':
Ciudades visitadas: 13
Distancia total: 2778 km
Ruta: Barcelona -> Hospitalet de Llobregat -> Zaragoza -> Valencia -> Alicante ... Gijón -> Bilbao -> Vigo

In [44]:
# --- Parte 4: Resolución del EXTRA ---

print(f"EXTRA: Buscando la mejor ciudad de origen (sobre las {len(matriz_limpia)} ciudades)...")

resultados = {}
mejor_distancia = float('inf')
mejor_ciudad = None

# Iteramos por cada ciudad de la matriz para probarla como origen
for ciudad in matriz_limpia.index:
    ruta, distancia = calcular_ruta_corta(matriz_limpia, ciudad)

    if isinstance(ruta, list): # Comprobamos que no haya dado error
        resultados[ciudad] = {'ruta': ruta, 'distancia': distancia}

        if distancia < mejor_distancia:
            mejor_distancia = distancia
            mejor_ciudad = ciudad

# Imprimimos la mejor ruta
print(f"\n¡MEJOR RUTA ENCONTRADA (de {len(matriz_limpia)} ciudades)!")
print(f"Ciudad de origen: {mejor_ciudad}")
print(f"Distancia total: {mejor_distancia:.0f} km")
print(f"\nRuta completa:")
print(" -> ".join(resultados[mejor_ciudad]['ruta']))


# Mostramos las 5 mejores y 5 peores ciudades de origen
print("TOP 5 mejores ciudades de origen:")
top_ciudades = sorted(resultados.items(), key=lambda item: item[1]['distancia'])[:5]
for i, (ciudad, data) in enumerate(top_ciudades, 1):
    print(f"{i}. {ciudad}: {data['distancia']:.0f} km")

print("\nTOP 5 peores ciudades de origen:")
peor_ciudades = sorted(resultados.items(), key=lambda item: item[1]['distancia'], reverse=True)[:5]
for i, (ciudad, data) in enumerate(peor_ciudades, 1):
    print(f"{i}. {ciudad}: {data['distancia']:.0f} km")

EXTRA: Buscando la mejor ciudad de origen (sobre las 13 ciudades)...

¡MEJOR RUTA ENCONTRADA (de 13 ciudades)!
Ciudad de origen: Barcelona
Distancia total: 2778 km

Ruta completa:
Barcelona -> Hospitalet de Llobregat -> Zaragoza -> Valencia -> Alicante -> Murcia -> Córdoba -> Sevilla -> Málaga -> Valladolid -> Gijón -> Bilbao -> Vigo
TOP 5 mejores ciudades de origen:
1. Barcelona: 2778 km
2. Hospitalet de Llobregat: 2784 km
3. Vigo: 2873 km
4. Sevilla: 2956 km
5. Córdoba: 2981 km

TOP 5 peores ciudades de origen:
1. Gijón: 3439 km
2. Bilbao: 3431 km
3. Zaragoza: 3415 km
4. Valladolid: 3357 km
5. Valencia: 3200 km